Repository 5tarlight/PumpkinGoguma, pull requests merged in 2022-02, with the labels that each got.

#1 Initiating dotnet
  .gitignore
  Program.cs
  goguma.csproj
Labels: size/S

#2 Yeah/console util
  .vscode/launch.json
  .vscode/tasks.json
  Program.cs
  Util/ConsoleUtil.cs
  goguma.csproj
Labels: size/L

#4 player hotpatch
  .gitignore
  Entity/Champion/BaseChampion.cs
  Entity/Champion/IChampion.cs
  Entity/Champion/TempPlayer.cs
  Hoguma.csproj
  Program.cs
  Util/ConsoleUtil.cs
  Util/PlayerManager.cs
Labels: size/L

#5 Sky/item
  Item/ConsumableEffect.cs
  Item/ConsumableItem.cs
  Item/EquipmentAbility.cs
  Item/EquipmentItem.cs
  Item/IItem.cs
  Item/Item.cs
  Item/ItemId.cs
  Item/ItemType.cs
  Item/OtherItem.cs
Labels: size/L

#6 Sky/inventory
  Inventory/Inventory.cs
  Inventory/InventoryItem.cs
  Inventory/SelectedItem.cs
  Item/IItem.cs
  Item/Item.cs
Labels: size/L

#7 Sky/inventory
  Entity/Champion/BaseChampion.cs
  Entity/Champion/IChampion.cs
  Entity/Champion/TempChampion.cs
  Entity/Champion/TempPlayer.cs
  Inventory/Inventory.cs
  Inventory/InventoryItem.cs
  Inventory/SelectedItem.cs
  Item/ConsumableEffect.cs
  Item/ConsumableItem.cs
  Item/EquipmentAbility.cs
  Item/EquipmentItem.cs
  Item/IItem.cs
  Item/Item.cs
  Item/ItemId.cs
  Item/ItemType.cs
  Item/OtherItem.cs
  Util/ConsoleUtil.cs
  Util/PlayerManager.cs
Labels: size/L

#8 YEAH - Load & save player data
  Entity/Champion/BaseChampion.cs
  Util/PlayerManager.cs
Labels: size/M

#9 Yeah/load player
  Program.cs
Labels: size/S

#10 Player Update
  .gitignore
  .vscode/launch.json
  .vscode/tasks.json
  Entity/Champion/BaseChampion.cs
  Entity/Champion/IChampion.cs
  Entity/Champion/TempChampion.cs
  Hoguma.csproj
  Inventory/Inventory.cs
  Inventory/InventoryItem.cs
  Inventory/SelectedItem.cs
  Item/ConsumableEffect.cs
  Item/ConsumableItem.cs
  Item/EquipmentAbility.cs
  Item/EquipmentItem.cs
  Item/IItem.cs
  Item/Item.cs
  Item/ItemId.cs
  Item/ItemType.cs
  Item/OtherItem.cs
  Program.cs
  Util/ConsoleUtil.cs
  Util/PlayerManager.cs
Labels: size/XL

#11 Sky/main menu
  Entity/Champion/BaseChampion.cs
  Entity/Champion/IChampion.cs
  Game/Main.cs
  Inventory/Inventory.cs
  Inventory/InventoryItem.cs
  Inventory/SelectedItem.cs
  Item/ConsumableEffect.cs
  Item/ConsumableItem.cs
  Item/EquipmentAbility.cs
  Item/EquipmentItem.cs
  Item/IItem.cs
  Item/Item.cs
  Item/ItemId.cs
  Item/ItemType.cs
  Item/OtherItem.cs
  Program.cs
  Util/ConsoleUtil.cs
Labels: size/L

#12 readme
  README.md
Labels: size/M

#14 Sky/inventory
  Game/Main.cs
  Inventory/EquipmentInv.cs
  Inventory/EquipmentInvItem.cs
  Inventory/Inventory.cs
  Item/ConsumableEffect.cs
  Item/ConsumableItem.cs
  Item/ConsumableType.cs
  Item/EquipmentAbility.cs
  Item/EquipmentItem.cs
  Item/EquipmentType.cs
  Item/IItem.cs
  Item/Item.cs
  Item/TestItemE.cs
  Item/TestItemO.cs
  Util/ConsoleUtil.cs
Labels: size/L

#15 add keybind, apply to code / fix load player bug, add load player action in main-menu
  Game/Main.cs
  Inventory/Inventory.cs
  Program.cs
  Util/ConsoleUtil.cs
  Util/Keybinds.cs
  Util/PlayerManager.cs
Labels: size/L

#17 add some util
  Util/ConsoleUtil.cs
Labels: size/M

#18 Yeah/Bug Fix
  Entity/Champion/BaseChampion.cs
  Entity/Champion/IChampion.cs
  Game/Main.cs
  Inventory/Inventory.cs
  Inventory/InventoryItem.cs
  Item/EquipmentAbility.cs
  Item/Item.cs
  Item/TestItemE.cs
  Program.cs
  Util/ConsoleUtil.cs
Labels: size/L

#23 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: size/L

#21 security patch 1
  SECURITY.md
Labels: size/S

#24 Create CONTRIBUTING.md
  CONTRIBUTING.md
Labels: size/XS

#25 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: size/M

#26 Revert "Update issue templates"
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: size/M

#27 Sky/bug fix
  Game/Main.cs
  Inventory/Inventory.cs
  Item/ConsumableItem.cs
  Item/EquipmentItem.cs
  Item/IItem.cs
  Item/Item.cs
  Program.cs
  Util/ConsoleUtil.cs
Labels: size/M
